// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"oa/internal/database"
	user3 "oa/internal/handler/user"
	"oa/internal/repository/user"
	user2 "oa/internal/service/user"
)

// Injectors from wire.go:

func BuildHandlers() (*Handlers, error) {
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	userRepositoryInterface := user.NewUserRepository(db)
	userServiceInterface := user2.NewUserService(userRepositoryInterface)
	userHandler := user3.NewUserHandler(userServiceInterface)
	client := database.NewRedis()
	data := database.NewData(db, client)
	handlers := NewHandlers(userHandler, data)
	return handlers, nil
}

// wire.go:

var DataBaseSet = wire.NewSet(database.NewDatabase, database.NewRedis, database.NewData)

var UserSet = wire.NewSet(user.NewUserRepository, user2.NewUserService, user3.NewUserHandler)
