// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"oa/internal/database"
	"oa/internal/handler/user"
)

// Injectors from wire.go:

func BuildHandlers() (*Handlers, error) {
	userHandler := user.NewUserHandler()
	db, err := database.NewDatabase()
	if err != nil {
		return nil, err
	}
	client := database.NewRedis()
	data := database.NewData(db, client)
	handlers := NewHandlers(userHandler, data)
	return handlers, nil
}

// wire.go:

var DataBaseSet = wire.NewSet(database.NewDatabase, database.NewRedis, database.NewData)

var UserSet = wire.NewSet(user.NewUserHandler)
