// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role 角色表
type Role struct {
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:角色ID" json:"id"`                                  // 角色ID
	Name        string         `gorm:"column:name;type:varchar(50);not null;uniqueIndex:name,priority:1;index:idx_name,priority:1;comment:角色名称" json:"name"` // 角色名称
	Code        string         `gorm:"column:code;type:varchar(50);not null;uniqueIndex:code,priority:1;index:idx_code,priority:1;comment:角色编码" json:"code"` // 角色编码
	Description *string        `gorm:"column:description;type:text;comment:角色描述" json:"description"`                                                         // 角色描述
	Level       *int32         `gorm:"column:level;type:tinyint;index:idx_level,priority:1;default:1;comment:角色级别：1-普通，2-中级，3-高级，99-超级管理员" json:"level"`     // 角色级别：1-普通，2-中级，3-高级，99-超级管理员
	Status      *int32         `gorm:"column:status;type:tinyint;index:idx_status,priority:1;default:1;comment:状态：0-禁用，1-启用" json:"status"`                  // 状态：0-禁用，1-启用
	IsSystem    *int32         `gorm:"column:is_system;type:tinyint;comment:是否系统角色：0-否，1-是（系统角色不可删除）" json:"is_system"`                                      // 是否系统角色：0-否，1-是（系统角色不可删除）
	SortOrder   *int32         `gorm:"column:sort_order;type:int;index:idx_sort_order,priority:1;comment:排序顺序" json:"sort_order"`                            // 排序顺序
	CreatedBy   *int64         `gorm:"column:created_by;type:bigint unsigned;index:created_by,priority:1;comment:创建人ID" json:"created_by"`                   // 创建人ID
	UpdatedBy   *int64         `gorm:"column:updated_by;type:bigint unsigned;index:updated_by,priority:1;comment:更新人ID" json:"updated_by"`                   // 更新人ID
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                            // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                            // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;index:idx_deleted_at,priority:1;comment:删除时间（逻辑删除）" json:"deleted_at"`                // 删除时间（逻辑删除）
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
