// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User 用户表
type User struct {
	ID          int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                                                 // 用户ID
	Username    string         `gorm:"column:username;type:varchar(50);not null;uniqueIndex:username,priority:1;index:idx_username,priority:1;comment:用户名" json:"username"` // 用户名
	Email       string         `gorm:"column:email;type:varchar(100);not null;uniqueIndex:email,priority:1;index:idx_email,priority:1;comment:邮箱" json:"email"`             // 邮箱
	Password    string         `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`                                                               // 密码
	Nickname    *string        `gorm:"column:nickname;type:varchar(50);comment:昵称" json:"nickname"`                                                                         // 昵称
	Avatar      *string        `gorm:"column:avatar;type:varchar(255);comment:头像URL" json:"avatar"`                                                                         // 头像URL
	Birthday    *time.Time     `gorm:"column:birthday;type:date;comment:生日" json:"birthday"`                                                                                // 生日
	Status      *int32         `gorm:"column:status;type:tinyint;index:idx_status,priority:1;default:1;comment:状态：0-禁用，1-启用" json:"status"`                                 // 状态：0-禁用，1-启用
	LastLoginAt *time.Time     `gorm:"column:last_login_at;type:timestamp;comment:最后登录时间" json:"last_login_at"`                                                             // 最后登录时间
	CreatedAt   *time.Time     `gorm:"column:created_at;type:timestamp;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`           // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                           // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp;index:idx_deleted_at,priority:1;comment:删除时间（逻辑删除）" json:"deleted_at"`                               // 删除时间（逻辑删除）
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
